[package]
name = "Aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
strum = "0.17.1"
strum_macros = "0.17.1"

[profile.release]
opt-level = 3
